// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fbuJuBeGGExNUPNJtI6MiITN6eyYPVA',
    appId: '1:659420842839:web:c2f37754088a87e104cc12',
    messagingSenderId: '659420842839',
    projectId: 'gradchat-f30c5',
    authDomain: 'gradchat-f30c5.firebaseapp.com',
    storageBucket: 'gradchat-f30c5.appspot.com',
    measurementId: 'G-0MW7N50MJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsA1YhzYVHwdVOQ-XSBhYHVFxsCuNRViw',
    appId: '1:659420842839:android:65c106a4ed28d3ff04cc12',
    messagingSenderId: '659420842839',
    projectId: 'gradchat-f30c5',
    storageBucket: 'gradchat-f30c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfX-kDOzh_V9wJkiPyJQyD6PmMU667GTk',
    appId: '1:659420842839:ios:bc3548f272c523d304cc12',
    messagingSenderId: '659420842839',
    projectId: 'gradchat-f30c5',
    storageBucket: 'gradchat-f30c5.appspot.com',
    iosClientId: '659420842839-q8nbcmvfrudctnnkge41bs55m6ecj0p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGraduationProject',
  );
}
